# Secrets Manager: the DATABASE_URL secret is fully Terraform-managed (its
# value is derived entirely from resources Terraform already created). The
# app-integration secrets (JWT, Slack, Google, GitHub, cron) are external —
# Terraform creates empty *shells* here; fill in real values after apply:
#
#   aws secretsmanager put-secret-value \
#     --secret-id $(terraform output -raw jwt_secret_arn) \
#     --secret-string "$(openssl rand -hex 32)"
#
# See infra/README.md for the full list of put-secret-value commands.

resource "random_password" "jwt_secret" {
  length  = 32
  special = false
}

resource "random_password" "cron_secret" {
  length  = 32
  special = false
}

resource "aws_secretsmanager_secret" "database_url" {
  name                    = "${var.project_name}/database-url"
  recovery_window_in_days = 0 # immediate delete on destroy — avoids a 7/30-day dangling-secret surprise during iteration
}

resource "aws_secretsmanager_secret_version" "database_url" {
  secret_id = aws_secretsmanager_secret.database_url.id
  secret_string = "postgresql://${aws_db_instance.flowboard.username}:${random_password.db.result}@${aws_db_instance.flowboard.address}:${aws_db_instance.flowboard.port}/${aws_db_instance.flowboard.db_name}"
}

# JWT_SECRET and CRON_SECRET are generated by Terraform (random, no external
# dependency) so they're fully managed end-to-end, unlike the OAuth/Slack
# secrets below which come from third-party consoles.

resource "aws_secretsmanager_secret" "jwt_secret" {
  name                    = "${var.project_name}/jwt-secret"
  recovery_window_in_days = 0
}

resource "aws_secretsmanager_secret_version" "jwt_secret" {
  secret_id     = aws_secretsmanager_secret.jwt_secret.id
  secret_string = random_password.jwt_secret.result
}

resource "aws_secretsmanager_secret" "cron_secret" {
  name                    = "${var.project_name}/cron-secret"
  recovery_window_in_days = 0
}

resource "aws_secretsmanager_secret_version" "cron_secret" {
  secret_id     = aws_secretsmanager_secret.cron_secret.id
  secret_string = random_password.cron_secret.result
}

# --- External secrets: empty shells, fill in after apply ---

resource "aws_secretsmanager_secret" "slack_signing_secret" {
  name                    = "${var.project_name}/slack-signing-secret"
  recovery_window_in_days = 0
}

resource "aws_secretsmanager_secret_version" "slack_signing_secret" {
  secret_id     = aws_secretsmanager_secret.slack_signing_secret.id
  secret_string = "changeme"
  lifecycle {
    ignore_changes = [secret_string] # value is set out-of-band after apply; don't fight manual updates
  }
}

resource "aws_secretsmanager_secret" "slack_bot_token" {
  name                    = "${var.project_name}/slack-bot-token"
  recovery_window_in_days = 0
}

resource "aws_secretsmanager_secret_version" "slack_bot_token" {
  secret_id     = aws_secretsmanager_secret.slack_bot_token.id
  secret_string = "changeme"
  lifecycle {
    ignore_changes = [secret_string]
  }
}

resource "aws_secretsmanager_secret" "google_client_secret" {
  name                    = "${var.project_name}/google-client-secret"
  recovery_window_in_days = 0
}

resource "aws_secretsmanager_secret_version" "google_client_secret" {
  secret_id     = aws_secretsmanager_secret.google_client_secret.id
  secret_string = "changeme"
  lifecycle {
    ignore_changes = [secret_string]
  }
}

resource "aws_secretsmanager_secret" "github_client_secret" {
  name                    = "${var.project_name}/github-client-secret"
  recovery_window_in_days = 0
}

resource "aws_secretsmanager_secret_version" "github_client_secret" {
  secret_id     = aws_secretsmanager_secret.github_client_secret.id
  secret_string = "changeme"
  lifecycle {
    ignore_changes = [secret_string]
  }
}
